update

diff --git a/rmanager b/rmanager
--- a/rmanager
+++ b/rmanager
@@ -1,6 +1,21 @@
 #!/bin/bash
 set -e
 
+# defer script
+__func_defered=()
+defer() {
+    __func_defered+=("$*")
+}
+do_defer() {
+    for ((i=${#__func_defered[@]}-1;i>=0;i--)); do
+        if ! eval "${__func_defered[i]}"; then
+            echo "eval cmd failed, cmd: \"${__func_defered[i]}\"" >&2
+        fi
+    done
+}
+trap do_defer EXIT
+# defer script end
+
 opt_label="rootdisk"
 opt_subvol="volumes"
 opt_prefix=""
@@ -12,7 +27,7 @@ err() {
     echo "$@" >&2
 }
 die() {
-    err "$@"
+    echo "$@" >&2
     exit 1
 }
 
@@ -28,28 +43,27 @@ do_uninit() {
 }
 
 
-list() {
+do_list() {
     ls -lha "${snapshot_prefix}"
 }
 
 # checkout [tag]
-checkout() {
-    local head branch tag
-    head=$(readlink "${snapshot_prefix}/current")
-    branch=${head%.*}
-
-    tag="$1"
-    [[ -z ${tag} ]] && tag="${branch}.$(date +%Y%m%d%H%M%S)"
+do_checkout() {
+    local current="$(readlink "${snapshot_prefix}/current")"
+    local tag="$1"
+    if [[ -z "${tag}" ]]; then
+        tag="${current%%.*}.$(date +%Y%m%d%H%M%S)"
+    fi
 
     if [[ ! -e "${snapshot_prefix}/${tag}" ]]; then
         btrfs subvol snapshot "${snapshot_prefix}/${head}" "${snapshot_prefix}/${tag}"
     fi
-
     rm "${snapshot_prefix}/current"
     ln -sfT "${tag}" "${snapshot_prefix}/current"
 }
 
-delete() {
+# delete tag...
+do_delete() {
     local tag
     for tag in "$@"; do
         if [[ -e "${snapshot_prefix}/${tag}" ]]; then
@@ -58,10 +72,31 @@ delete() {
     done
 }
 
-main() {
-    if [[ $UID != '0' ]]; then
-        die "can not manager rootfs as ${USER}"
+# exec [-u user] tag cmd...
+do_exec() {
+    local opt_user=root
+    while (($#)); do
+        case $1 in
+            -u | --user)
+                opt_user="$2"
+                shift 2
+                ;;
+            *)
+                break;;
+        esac
+    done
+    local tag="$1"
+    shift
+    if [[ ! -e "${snapshot_prefix}/${tag}" ]]; then
+        die "exec failed, check tag: ${snapshot_prefix}/${tag}"
     fi
+
+    for cmd in "$@"; do
+        (cd "${snapshot_prefix}/${tag}" && su "${opt_user}" -c "${cmd}")
+    done
+}
+
+main() {
     while (( $# )); do
         case $1 in
             -L | --label)
@@ -81,11 +116,30 @@ main() {
                 ;;
         esac
     done
+    defer do_uninit
     do_init
-    trap "do_uninit" EXIT
-    local action="$1"
-    shift
-    $action "$@"
+
+    case "${1}" in
+        list)
+            shift 1
+            do_list "$@"
+            ;;
+        checkout)
+            shift 1
+            do_checkout "$@"
+            ;;
+        delete)
+            shift 1
+            do_delete "$@"
+            ;;
+        exec)
+            shift 1
+            do_exec "$@"
+            ;;
+        *)
+            die "unknown action: $*"
+            ;;
+    esac
 }
 
 main "$@"
