update

diff --git a/rmanager b/rmanager
--- a/rmanager
+++ b/rmanager
@@ -1,22 +1,20 @@
 #!/usr/bin/env bash
-set -o errexit
-set -o pipefail
-set -o nounset
+set -euo pipefail
+
+script_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
+script_name="$(basename "${BASH_SOURCE[0]}")"
 
 info() {
-    echo "[info]" "$@"
+    echo "Info: $*"
 }
 
-err() {
-    echo "[error]" "$@" 2>&1
+error() {
+    echo "Error: $*" >&2
 }
 
 die() {
-    local code="$1"
-    shift
-
-    err "$@"
-    exit "${code}"
+    error "Error: $*"
+    exit 1
 }
 
 __func_defered=()
@@ -24,7 +22,7 @@ do_defer() {
     local i
     for ((i=${#__func_defered[@]}-1;i>=0;i--)); do
         if ! eval "${__func_defered[i]}"; then
-            die 1 "eval cmd failed, cmd: \"${__func_defered[i]}\""
+            die "eval cmd failed, cmd: \"${__func_defered[i]}\""
         fi
     done
 }
@@ -66,7 +64,7 @@ do_snapshot() {
 
     local tag
     for tag in "${tags[@]}"; do
-        btrfs subvol snapshot "${snapshot_prefix}/${base_tag}" "${snapshot_prefix}/${tag}" || die 255 "btrfs cannot snapshot '${base_tag}' to ${tag}"
+        btrfs subvol snapshot "${snapshot_prefix}/${base_tag}" "${snapshot_prefix}/${tag}" || die "btrfs cannot snapshot '${base_tag}' to ${tag}"
     done
 }
 
@@ -77,7 +75,7 @@ do_delete() {
 
     local tag
     for tag in "$@"; do
-        btrfs subvol delete -R "${snapshot_prefix}/${tag}" || die 255 "btrfs cannot delete subvol '${tag}'"
+        btrfs subvol delete -R "${snapshot_prefix}/${tag}" || die "btrfs cannot delete subvol '${tag}'"
     done
 }
 
@@ -111,7 +109,7 @@ do_checkout() {
         base_tag="$(basename $(realpath "${rootdisk_prefix}/rootfs"))"
     fi
 
-    local tag="${1:-}"
+    local tag="$1"
     if [[ -z "${tag}" ]]; then
         local branch version
         IFS='.' read -r branch version <<<"${base_tag}"
@@ -160,7 +158,7 @@ main() {
             do_checkout "$@"
             ;;
         *)
-            die 255 "undefined command '$1'"
+            die "undefined command '$1'"
             ;;
     esac
 }
